// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '🏗️ Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: '🚀 Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: '⚙️ Backend',
      items: [{ type: 'autogenerated', dirName: 'backend' }],
    },
    {
      type: 'category',
      label: '🎨 Frontend',
      items: [{ type: 'autogenerated', dirName: 'frontend' }],
    },
    {
      type: 'category',
      label: '📋 SOPs',
      items: [{ type: 'autogenerated', dirName: 'sops' }],
    },
    {
      type: 'category',
      label: '🛠️ Scripts',
      items: [{ type: 'autogenerated', dirName: 'scripts' }],
    },
  ],
};

export default sidebars;
