"""added otp columns to user model

Revision ID: 324713d6732f
Revises: ded1b14398dd
Create Date: 2026-02-27 13:48:11.040727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324713d6732f'
down_revision = 'ded1b14398dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
