"""consolidate_connected_accounts_and_email_connections

Revision ID: dfca4bea8251
Revises: 9257d9f8cc12
Create Date: 2026-02-28 16:29:07.180758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfca4bea8251'
down_revision = '9257d9f8cc12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('scopes', sa.JSON(), nullable=True))
    op.add_column('connected_accounts', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connected_accounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    op.alter_column('connected_accounts', 'access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('connected_accounts', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('connected_accounts', 'token_expiry',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_unique_constraint(None, 'email_extractions', ['id'])
    op.add_column('emails', sa.Column('connected_account_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'emails', ['id'])
    op.drop_constraint(op.f('emails_email_connection_id_fkey'), 'emails', type_='foreignkey')
    op.create_foreign_key(None, 'emails', 'connected_accounts', ['connected_account_id'], ['id'])
    op.drop_column('emails', 'email_connection_id')
    
    # Drop email_connections related objects last
    op.drop_index(op.f('ix_email_connections_provider'), table_name='email_connections')
    op.drop_table('email_connections')
    
    op.create_unique_constraint(None, 'jobs', ['id'])
    op.create_unique_constraint(None, 'llm_transactions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_transactions', type_='unique')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.add_column('emails', sa.Column('email_connection_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.create_foreign_key(op.f('emails_email_connection_id_fkey'), 'emails', 'email_connections', ['email_connection_id'], ['id'])
    op.drop_constraint(None, 'emails', type_='unique')
    op.drop_column('emails', 'connected_account_id')
    op.drop_constraint(None, 'email_extractions', type_='unique')
    op.alter_column('connected_accounts', 'token_expiry',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('connected_accounts', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('connected_accounts', 'access_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('connected_accounts', 'updated_at')
    op.drop_column('connected_accounts', 'revoked_at')
    op.drop_column('connected_accounts', 'scopes')
    op.create_table('email_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('email_connections_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_connections_pkey'))
    )
    op.create_index(op.f('ix_email_connections_provider'), 'email_connections', ['provider'], unique=False)
    # ### end Alembic commands ###
